#!/bin/bash

-() { exit 1; }

readonly NAME="$0"
readonly ROOT="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

cd "$ROOT/.." ||-

usage() {
    printf 'usage: %s [0-9]+.[0-9]+.[0-9]+\n' "$0" >&2
    printf '  current ' >&2
    grep '^version =' Cargo.toml >&2
    exit 1
}

if [[ -n $(git status --porcelain) ]]; then
    printf 'error: working directory is dirty\n' >&2
    exit 1
fi

if [[ $(git symbolic-ref --short -q HEAD) != "main" ]]; then
    printf 'error: not on branch main\n' >&2
    exit 1
fi

(($#==1)) || usage
readonly VERSION="$1"
[[ $VERSION =~ [0-9]+.[0-9]+.[0-9]+ ]] || usage

sed -i 's/^version =.*/version = "'"$VERSION"'"/' Cargo.toml ||-
util/smoke ||-
git add -A ||-
git commit -m "Bump version to $VERSION" ||-
git tag "v$VERSION" ||-
printf 'successfully committed and tagged, to push run:\n'
printf 'git push origin main %s\n' "v$VERSION"
