#!/bin/bash

# A hacky script to scrape some of the "known values" from llvm/CMakeLists.txt
#
# Ideally some stable interface to LLVM's CMake will replace this eventually.

set -u

-() { exit 1; }

readonly NAME="$0"
readonly ROOT="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
readonly VALUES="$ROOT/../values"

usage() {
    printf 'usage: %s PATH-TO-LLVM-PROJECT\n' "$NAME" >&2
    exit 1
}

(($#==1)) || usage
readonly PATH_TO_LLVM_PROJECT="$1"

cmake_array_to_rust_array() {
    sed -e 's/;/", "/g' -e 's/\(.*\)/["\1"]\n/'
}

rm -rf "$VALUES"/scrape_bin
cmake -S "$PATH_TO_LLVM_PROJECT/llvm" -B "$VALUES"/scrape_bin -DCMAKE_BUILD_TYPE=Release
cmake -S "$PATH_TO_LLVM_PROJECT/llvm" -B "$VALUES"/scrape_bin -DLLVM_ENABLE_PROJECTS=unknown 2>&1 \
    | tr '\n' ' ' \
    | sed "s/.*unknown isn't a known project: *\([^.]*\)\..*/\1/" \
    | cmake_array_to_rust_array \
    > "$VALUES/llvm_all_projects.in"
cmake -S "$PATH_TO_LLVM_PROJECT/llvm" -B "$VALUES"/scrape_bin -DLLVM_ENABLE_PROJECTS=llvm -DLLVM_TARGETS_TO_BUILD=unknown 2>&1 \
    | tr '\n' ' ' \
    | sed 's/.*Core tier targets: *\([^ ]*\) *Known experimental targets:.*/\1/' \
    | cmake_array_to_rust_array \
    > "$VALUES/llvm_all_targets.in"
cmake -S "$PATH_TO_LLVM_PROJECT/llvm" -B "$VALUES"/scrape_bin -DLLVM_ENABLE_PROJECTS=llvm -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_RUNTIMES=unknown 2>&1 \
    | tr '\n' ' ' \
    | sed 's/.*Supported runtimes are: *\([^ ]*\) *.*/\1/' \
    | cmake_array_to_rust_array \
    > "$VALUES/llvm_all_runtimes.in"
rm -rf "$VALUES"/scrape_bin

sed 's/^\[/["Native", /' <"$VALUES/llvm_all_targets.in" >"$VALUES/llvm_all_targets_alt.in"
